baseurl = "http://xren615.github.io"
title = "INCH2"
languageCode = "en-us"

theme = "hugo-hello-programmer-theme"

paginate = 3

disqusShortname = "riren"
googleAnalytics = "UA-76515451-1"

[author]
    name = "Rick"
    email = "xinyuyangren@foxmail.com"